server:
  port: 8085
spring:
  application:
    name: XsustainCRM
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/XsustainCRMFDataBase
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: workbottn@gmail.com
    password: cufzgbpnihwgbllr
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
token:
  secret:
    key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
super:
  user:
    mail: fn.mohsen.tu@gmail.com

retry:
  config:
    maxAttempts: 3
    backoffDelay: 3000